services:
  frontend:
    build: ./rubiks-rush-fe
    container_name: rubiks-rush-frontend
    ports:
      - "${FRONTEND_PORT}:80"

  backend:
    build: ./rubiks-rush-be
    container_name: rubiks-rush-backend
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      DATASOURCE_URL: jdbc:mysql://database:3306/rubiks-rush-db
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: rubiks-rush-database
    environment:
      MYSQL_DATABASE: rubiks-rush-db
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3333:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data:

